import React, { useState } from 'react';
import AppLayout from '../components/layout/AppLayout';

const ORG = 'Contoso Defense Corp';
const TENANT = 'contoso.onmicrosoft.com';
const REPORT_DATE = new Date().toISOString();
const SCAN_DATE = new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString();

const CONTROLS = [
  {
    id: 'AC.L2-3.1.1',
    family: 'Access Control',
    title: 'Authorized Access Control',
    status: 'pass' as const,
    findings: [
      '5 active Conditional Access policies detected.',
      'At least one policy enforces grant controls.',
    ],
    evidenceHash: 'a3f8c2d14e7b9052f6a1c3d8e5b2f094a7c1d3e6f8b2a5c9d1e4f7a0b3c6d8e2',
    remediation: null,
  },
  {
    id: 'AC.L2-3.1.2',
    family: 'Access Control',
    title: 'Transaction & Function Control',
    status: 'pass' as const,
    findings: [
      '6 role assignments found.',
      'Role assignments appear to follow least-privilege principles.',
    ],
    evidenceHash: 'b7e2a4d6f0c3e8a1b5d9f2c7e4a0b8d3f6c1e5a9b4d7f0c2e6a3b8d1f4c9e2a5',
    remediation: null,
  },
  {
    id: 'AU.L2-3.3.1',
    family: 'Audit & Accountability',
    title: 'System Audit',
    status: 'pass' as const,
    findings: [
      '27 activity log events found (capped at query limit).',
      'Log categories present: Administrative, Security, Policy, Recommendation.',
      'Critical audit categories (Administrative/Security) are present.',
    ],
    evidenceHash: 'c9d4f1a6e3b8c2f5a0d7e4b1c8f3a6d9e2b5c0f7a4d1e8b3c6f9a2d5e0b7c4f1',
    remediation: null,
  },
  {
    id: 'IA.L2-3.5.1',
    family: 'Identification & Authentication',
    title: 'Identification',
    status: 'pass' as const,
    findings: [
      '47 users found. 47 unique UPNs.',
      '2 disabled accounts present — review for cleanup.',
      '3 guest accounts tracked.',
    ],
    evidenceHash: 'd1e5b9c4f2a7e0d3b8f5c2a9e6d1b4c7f0a5e2d9b6c3f0a7e4d1b8c5f2a9e6d3',
    remediation: 'Review and formally deprovision 2 disabled accounts.',
  },
  {
    id: 'IA.L2-3.5.2',
    family: 'Identification & Authentication',
    title: 'Authentication (MFA)',
    status: 'warning' as const,
    findings: [
      'MFA registration rate: 91.1% (41/45 users).',
      'MFA registration is below 95% — needs improvement.',
    ],
    evidenceHash: 'e4f0a3d8b2c6f1a5e9d2b7c4f8a1e6d0b3c7f2a8e5d1b9c4f6a2e0d7b5c3f8a4',
    remediation: 'Enforce MFA registration via Conditional Access policy for 4 non-enrolled users. Target: 100% enrollment within 14 days.',
  },
  {
    id: 'SC.L2-3.13.1',
    family: 'System & Communications Protection',
    title: 'Boundary Protection',
    status: 'fail' as const,
    findings: [
      '3 NSGs found.',
      'CRITICAL: NSG "dev-nsg" allows inbound port 3389 from any source (0.0.0.0/0).',
    ],
    evidenceHash: 'f6a2e8d4b0c5f3a9e7d1b6c2f4a8e3d0b7c1f5a2e9d6b4c0f8a5e2d9b3c7f1a6',
    remediation: 'Immediately restrict or remove the "Allow-RDP-Any" rule on dev-nsg. Replace with a specific IP source (jump-host) or deploy Azure Bastion.',
  },
];

const STATUS_CFG = {
  pass: { label: 'PASS', row: 'bg-green-500/5', badge: 'bg-green-500/20 text-green-400 border-green-500/30', icon: '✓' },
  warning: { label: 'WARNING', row: 'bg-amber-500/5', badge: 'bg-amber-500/20 text-amber-400 border-amber-500/30', icon: '⚠' },
  fail: { label: 'FAIL', row: 'bg-red-500/5', badge: 'bg-red-500/20 text-red-400 border-red-500/30', icon: '✗' },
};

function generateTextReport(): string {
  const passing = CONTROLS.filter((c) => c.status === 'pass').length;
  const failing = CONTROLS.filter((c) => c.status === 'fail').length;
  const warnings = CONTROLS.filter((c) => c.status === 'warning').length;
  const rate = ((passing / CONTROLS.length) * 100).toFixed(1);

  const lines: string[] = [
    '================================================================',
    '        CMMC 2.0 LEVEL 2 COMPLIANCE REPORT',
    '================================================================',
    '',
    `Organization : ${ORG}`,
    `Azure Tenant : ${TENANT}`,
    `Report Date  : ${new Date(REPORT_DATE).toLocaleString()}`,
    `Last Scan    : ${new Date(SCAN_DATE).toLocaleString()}`,
    `Generated By : CMMC Dashboard (Automated)',`,
    '',
    '----------------------------------------------------------------',
    '  EXECUTIVE SUMMARY',
    '----------------------------------------------------------------',
    '',
    `  Controls Monitored : 6`,
    `  Passing            : ${passing}`,
    `  Failing            : ${failing}`,
    `  Warnings           : ${warnings}`,
    `  Compliance Rate    : ${rate}%`,
    '',
    '----------------------------------------------------------------',
    '  CONTROL RESULTS',
    '----------------------------------------------------------------',
    '',
  ];

  for (const c of CONTROLS) {
    const cfg = STATUS_CFG[c.status];
    lines.push(`  [${cfg.label.padEnd(7)}]  ${c.id}  —  ${c.title}`);
    lines.push(`  Family: ${c.family}`);
    lines.push('  Findings:');
    c.findings.forEach((f) => lines.push(`    • ${f}`));
    if (c.remediation) {
      lines.push('  Remediation Required:');
      lines.push(`    ${c.remediation}`);
    }
    lines.push(`  Evidence Hash (SHA-256): ${c.evidenceHash}`);
    lines.push('');
  }

  lines.push('----------------------------------------------------------------');
  lines.push('  REMEDIATION PRIORITY');
  lines.push('----------------------------------------------------------------');
  lines.push('');
  const needsAction = CONTROLS.filter((c) => c.remediation);
  needsAction.forEach((c, i) => {
    lines.push(`  ${i + 1}. ${c.id} (${STATUS_CFG[c.status].label})`);
    lines.push(`     ${c.remediation}`);
    lines.push('');
  });

  lines.push('================================================================');
  lines.push('  This report was generated automatically by the CMMC Dashboard.');
  lines.push('  Evidence hashes verify data integrity at time of collection.');
  lines.push('================================================================');

  return lines.join('\n');
}

export default function ReportsPage() {
  const [downloading, setDownloading] = useState(false);

  const passing = CONTROLS.filter((c) => c.status === 'pass').length;
  const failing = CONTROLS.filter((c) => c.status === 'fail').length;
  const warnings = CONTROLS.filter((c) => c.status === 'warning').length;
  const rate = ((passing / CONTROLS.length) * 100).toFixed(1);

  const downloadTxt = () => {
    setDownloading(true);
    const text = generateTextReport();
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cmmc-compliance-report-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => setDownloading(false), 800);
  };

  const downloadJson = () => {
    const data = {
      organization: ORG,
      tenant: TENANT,
      reportDate: REPORT_DATE,
      lastScan: SCAN_DATE,
      summary: { total: CONTROLS.length, passing, failing, warnings, complianceRate: rate },
      controls: CONTROLS,
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cmmc-compliance-report-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const printPdf = () => window.print();

  return (
    <AppLayout>
      <div className="max-w-4xl space-y-6">
        {/* Header + actions */}
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-2xl font-bold">Compliance Report</h1>
            <p className="text-sm text-slate-400 mt-1">
              {ORG} &bull; Generated {new Date(REPORT_DATE).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>
          <div className="flex gap-2 flex-wrap justify-end">
            <button
              onClick={downloadTxt}
              disabled={downloading}
              className="px-4 py-2 bg-navy-700 hover:bg-navy-600 border border-navy-600 rounded-lg text-xs font-medium text-slate-300 transition-colors"
            >
              {downloading ? 'Downloading…' : '↓ Download .txt'}
            </button>
            <button
              onClick={downloadJson}
              className="px-4 py-2 bg-navy-700 hover:bg-navy-600 border border-navy-600 rounded-lg text-xs font-medium text-slate-300 transition-colors"
            >
              ↓ Download JSON
            </button>
            <button
              onClick={printPdf}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-500 rounded-lg text-xs font-medium text-white transition-colors"
            >
              Print / Save PDF
            </button>
          </div>
        </div>

        {/* Org info banner */}
        <div className="bg-navy-800 border border-navy-600 rounded-xl p-5 grid grid-cols-3 gap-4 text-sm">
          <div>
            <p className="text-[10px] uppercase tracking-wider text-slate-500 mb-1">Organization</p>
            <p className="text-slate-200 font-medium">{ORG}</p>
          </div>
          <div>
            <p className="text-[10px] uppercase tracking-wider text-slate-500 mb-1">Azure Tenant</p>
            <p className="text-slate-200 font-medium">{TENANT}</p>
          </div>
          <div>
            <p className="text-[10px] uppercase tracking-wider text-slate-500 mb-1">Last Scan</p>
            <p className="text-slate-200 font-medium">{new Date(SCAN_DATE).toLocaleString()}</p>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-5 gap-3">
          {[
            { label: 'Controls Assessed', value: CONTROLS.length, color: 'text-blue-400' },
            { label: 'Passing', value: passing, color: 'text-green-400' },
            { label: 'Failing', value: failing, color: 'text-red-400' },
            { label: 'Warnings', value: warnings, color: 'text-amber-400' },
            { label: 'Compliance Rate', value: `${rate}%`, color: 'text-white' },
          ].map((s) => (
            <div key={s.label} className="bg-navy-700 border border-navy-600 rounded-xl p-4 text-center">
              <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
              <p className="text-[10px] uppercase tracking-wider text-slate-500 mt-1">{s.label}</p>
            </div>
          ))}
        </div>

        {/* Control results */}
        <div className="bg-navy-800 border border-navy-600 rounded-xl overflow-hidden">
          <div className="px-5 py-3 border-b border-navy-600">
            <h2 className="text-sm font-semibold">Control Assessment Results</h2>
          </div>

          <div className="divide-y divide-navy-700">
            {CONTROLS.map((c) => {
              const cfg = STATUS_CFG[c.status];
              return (
                <div key={c.id} className={`p-5 ${cfg.row}`}>
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-3">
                      <span className={`text-xs font-bold px-2 py-0.5 rounded border ${cfg.badge}`}>
                        {cfg.icon} {cfg.label}
                      </span>
                      <div>
                        <span className="text-xs font-mono text-slate-400">{c.id}</span>
                        <span className="text-slate-600 mx-2">·</span>
                        <span className="text-sm font-semibold text-slate-200">{c.title}</span>
                      </div>
                    </div>
                    <span className="text-[10px] text-slate-500 flex-shrink-0">{c.family}</span>
                  </div>

                  <div className="space-y-1 mb-3">
                    {c.findings.map((f, i) => (
                      <p key={i} className="text-xs text-slate-300">&ndash; {f}</p>
                    ))}
                  </div>

                  {c.remediation && (
                    <div className="bg-navy-900/50 border border-amber-500/20 rounded-lg px-3 py-2 mb-3">
                      <p className="text-[10px] uppercase tracking-wider text-amber-500 mb-0.5">Remediation Required</p>
                      <p className="text-xs text-slate-300">{c.remediation}</p>
                    </div>
                  )}

                  <code className="text-[10px] text-slate-600 font-mono">
                    SHA-256: {c.evidenceHash}
                  </code>
                </div>
              );
            })}
          </div>
        </div>

        {/* Remediation summary */}
        {CONTROLS.some((c) => c.remediation) && (
          <div className="bg-navy-800 border border-navy-600 rounded-xl p-5">
            <h2 className="text-sm font-semibold mb-4">Remediation Priority</h2>
            <div className="space-y-3">
              {CONTROLS.filter((c) => c.remediation).map((c, i) => (
                <div key={c.id} className="flex gap-4">
                  <div className="w-6 h-6 rounded-full bg-navy-700 border border-navy-600 flex items-center justify-center flex-shrink-0 text-xs text-slate-400 font-bold">
                    {i + 1}
                  </div>
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-xs font-mono text-slate-400">{c.id}</span>
                      <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded border ${STATUS_CFG[c.status].badge}`}>
                        {STATUS_CFG[c.status].label}
                      </span>
                    </div>
                    <p className="text-xs text-slate-300">{c.remediation}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        <p className="text-[10px] text-slate-600 text-center pb-4">
          This report was automatically generated by the CMMC Dashboard. Evidence hashes verify data integrity at time of collection.
          CMMC 2.0 Level 2 &bull; NIST SP 800-171 &bull; {new Date(REPORT_DATE).toLocaleDateString()}
        </p>
      </div>
    </AppLayout>
  );
}
